### ISSUE TITLE
JS ERROR: ImportError: No JS module 'cgjs' found in search path

### ISSUE THREAD

**Issue by sonnyp** [cgjs/cgjs#10]
On Arch Linux with `yarn global add cgjs`

* gjs: 1:1.52.1-1
* cgjs: 0.1.25

```
sonny@pikachu ~ % cgjs --help

(gjs:11721): Gjs-WARNING **: 17:16:10.606: JS ERROR: ImportError: No JS module 'cgjs' found in search path
@/home/sonny/.yarn/bin/cgjs:37:1
@/home/sonny/.yarn/bin/cgjs:4:2

Script /home/sonny/.yarn/bin/cgjs threw an exception
```

**Comment by WebReflection** [comment]
have you tried with npm ?

**Comment by sonnyp** [comment]
I didn't think about it. Works fine with npm.

**Comment by WebReflection** [comment]
I guess yarn put the module inside yarn folder but the bin inside npm bin folder ... I'm not sure I want to fix this one though ... it looks more like a yarn issue

**Comment by sonnyp** [comment]
Indeed.

`yarn global add cgjs`

bin: 
` ~/.yarn/bin/cgjs`

lib:
`~/.config/yarn/global/node_modules/cgjs`

I'd be happy to contribute a fix but I can't think of a proper way to address this.

**Comment by sonnyp** [comment]
cgjs could check if the bin path is `~/.yarn/bin` and use `~/.config/yarn/global/node_modules/cgjs` if it is the case.

It'll break for non default installation directory but that's an edge case for which a CGJS_LIB_DIR env var could be used.

What do you think?

**Comment by ewnd9** [comment]
Just for reference on my system:

```sh
# npm
$ ls -al ~/.npm-packages/bin/cgjs
lrwxrwxrwx 1 ewnd9 ewnd9 30 Apr 15 22:04 /home/ewnd9/.npm-packages/bin/cgjs -> ../lib/node_modules/cgjs/cg.js
# yarn
$ ls -al ~/.yarn/bin/cgjs
lrwxrwxrwx 1 ewnd9 ewnd9 49 Apr 15 22:02 /home/ewnd9/.yarn/bin/cgjs -> ../../.config/yarn/global/node_modules/cgjs/cg.js
```

**Comment by WebReflection** [comment]
> What do you think?

I think I should use Glib env to check bin paths instead of the guessing circus I am using now. The problem is that using cgjs directly as script instead of a global installation with a bin would fail too.

A combination of env checks and fallback to current circus might be better.

**Comment by WebReflection** [comment]
OK, current version `0.1.26` works on yarn too.

It's not a perfect solution but at this time it should be enough.

**Comment by sonnyp** [comment]
Works for me, thanks.

Can you remove the wontfix tag?
