### ISSUE TITLE
monorepo

### ISSUE THREAD

**Issue by sonnyp** [cgjs/cgjs#12]
I'd like to propose cgjs to adopt a monorepo approach.

It makes everything easier for users, contributors and maintainers.

Optional but https://github.com/lerna/lerna helps a lot with maintainance and inter dependencies.

We use it at https://github.com/xmppjs/xmpp.js/ and it's been of great help.

**Comment by WebReflection** [comment]
that means all repos now would disappear, right?

**Comment by sonnyp** [comment]
yes

**Comment by WebReflection** [comment]
is it possible to propose mono-cgjs and then eventually rename it once everything is fine? current setup might not be as straight forward to work with but it's been tested and it works without many issues so far

**Comment by sonnyp** [comment]
Are you proposing mono-cgjs as a npm module? I didn't mean to suggest the cgjs project should become a single npm package, I think using namespaced npm modules is the best approach for cgjs (we do that on xmpp.js too). What I meant to suggest is that the development of cgjs core and modules happen in the same git repository while keeping the npm modules separated. See https://github.com/xmppjs/xmpp.js/tree/master/packages . Lerna makes this super easy.

The only drawback is that users cannot use git URLs as dependencies in their package.json anymore for @cgjs/* packages.

My idea was to create a new "monorepo" branch on my fork https://github.com/sonnyp/cgjs, and "import" all repos with their commits then send a PR.

**Comment by sonnyp** [comment]
@WebReflection no need to decide if you like it now, if you're open about the idea, I can make the PR and we can discuss this further there.

**Comment by WebReflection** [comment]
> The only drawback is that ...

to be clear, I don't want all projects inside CGJS, I want only what's usable, as it is now:
https://github.com/cgjs/cgjs/blob/master/package.json#L31-L43

**Comment by sonnyp** [comment]
@WebReflection makes sense, do you want me to preserve git commits ?

**Comment by sonnyp** [comment]
If so, each module commits will be imported into the branch.

**Comment by WebReflection** [comment]
sorry @sonnyp I'm not too familiar with the learn approach, so I might just learn something.

If you feel like spending time to overall improve current contribution ease, I'm all up for it, 'cause this project **really** needs other devs beside me to help growing up with at least basic core modules features.

Feel free to move on with a PR, I'll try to find time ASAP to review that.

Thank you!

**Comment by sonnyp** [comment]
I didn't imported the git history of each packages because there were not significantly meaningful.

https://github.com/cgjs/cgjs/pull/13

**Comment by sonnyp** [comment]
@WebReflection that is great to hear, a monorepo approach is definitely gonna make contributing easier. I already have some code to contribute and I'm looking forward.

Adding me to the github project would help even further but I'd understand if you'd rather not for the time being.
