### ISSUE TITLE
`pnpm` compatibility

### ISSUE THREAD

**Issue by ewnd9** [cgjs/cgjs#14]
To continue exploration of installation methods, [`pnpm`](https://github.com/pnpm/pnpm) experience:   

```sh
$ pnpm install -g cgjs
$ $(pnpm bin -g)/cgjs

(gjs:8328): Gjs-WARNING **: JS ERROR: Error: unable to find buffer
/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs/node_modules/@cgjs/buffer
/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/@cgjs/buffer
@/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs/cgjs/core.js:35:17
@/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs/cgjs/core.js:8:3
@/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs/cgjs/core.js:1:1
@/home/ewnd9/.npm-packages/bin/../pnpm-global/1/node_modules/cgjs/cg.js:67:25
@/home/ewnd9/.npm-packages/bin/../pnpm-global/1/node_modules/cgjs/cg.js:58:3
@/home/ewnd9/.npm-packages/bin/../pnpm-global/1/node_modules/cgjs/cg.js:4:2
```

Mine approach from #11 also doesn't work

```sh
$ pnpm install -g ewnd9/cgjs#patch-1
$ $(pnpm bin -g)/cgjs                                              

(gjs:8986): Gjs-WARNING **: JS ERROR: Error: unable to find buffer
/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs/node_modules/@cgjs/buffer
/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/@cgjs/buffer
@/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs/cgjs/core.js:35:17
@/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs/cgjs/core.js:8:3
@/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs/cgjs/core.js:1:1
@/home/ewnd9/.npm-packages/bin/../pnpm-global/1/node_modules/cgjs/cg.js:68:25
@/home/ewnd9/.npm-packages/bin/../pnpm-global/1/node_modules/cgjs/cg.js:59:3
@/home/ewnd9/.npm-packages/bin/../pnpm-global/1/node_modules/cgjs/cg.js:4:2
```

The main difference between `pnpm` and `npm` / `yarn` is that it uses hard links to preserve free space on a disk

```sh
$ ls -al $(pnpm bin -g)/cgjs
-rwxr-xr-x 1 ewnd9 ewnd9 1971 Apr 16 23:24 /home/ewnd9/.npm-packages/bin/cgjs
```

According to stacktraces above, `cgjs` is installed in `/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs` which is a symlink

```sh
$ ls -al /home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs                                                                                  
lrwxrwxrwx 1 ewnd9 ewnd9 49 Apr 16 23:35 /home/ewnd9/.npm-packages/pnpm-global/1/node_modules/cgjs -> .registry.npmjs.org/cgjs/0.1.26/node_modules/cgjs
```

Children node_modules are placed nearby:

```sh
$ ls -al /home/ewnd9/.npm-packages/pnpm-global/1/node_modules/.registry.npmjs.org/cgjs/0.1.26/node_modules/@cgjs/buffer
lrwxrwxrwx 1 ewnd9 ewnd9 56 Apr 16 23:23 /home/ewnd9/.npm-packages/pnpm-global/1/node_modules/.registry.npmjs.org/cgjs/0.1.26/node_modules/@cgjs/buffer -> ../../../../@cgjs/buffer/0.1.0/node_modules/@cgjs/buffer
```

So the actual location of not found `@cgjs/buffer` is `/home/ewnd9/.npm-packages/pnpm-global/1/node_modules/.registry.npmjs.org/@cgjs/buffer/0.1.0/node_modules/@cgjs/buffer`

---

I don't use `pnpm` daily, just hoped to quickly prove my point from #11 :smile: 

Nevertheless I hope it is worth to be documented, feel free to close as won't fix

**Comment by WebReflection** [comment]
are you sure all of them create a symlink through the `bin` ? I might rethink your PR, I think I didn't get that

**Comment by ewnd9** [comment]
I'm certain of `npm` / `yarn`: you need a `bin` directory with binaries only to add it to `$PATH` for convenience and separate `node_modules` directory with sources and children `node_modules` for module resolution.

Do you think there might be cases when a package manager is copying to `bin` instead of symlinking? How does module resolution figures out children `node_modules` then?

**Comment by WebReflection** [comment]
> How does module resolution figures out children node_modules then?

that's the circus I'm doing right now. I've been stupid enough to not double check the Symlink "theory", thought those were files with specific paths inside or something similar ... if every tool is symlinking though, I agree it might be OK.

**however**, I am not sure about the `npx` case, or when the `.bin` is reached manually through the folder. That is probably not a symlink, or is it?

**Comment by ewnd9** [comment]
> I am not sure about the npx case, or when the .bin is reached manually through the folder. That is probably not a symlink, or is it?

`.bin` in local node_modules is also a symlink

```sh
$ npm i cgjs
$ ls -al ./node_modules/.bin/cgjs
lrwxrwxrwx 1 ewnd9 ewnd9 13 Apr 17 01:00 ./node_modules/.bin/cgjs -> ../cgjs/cg.js
```

Checking `npx` was a bit harder since it reinstalls a package every time and remove it after exiting (you have to remove all global installation of `cgjs` for reproduction, it reuses binaries from `$PATH` if possible)

```sh
$ npx -p cgjs -c 'echo $PATH && tail' &
$ ls -al /home/ewnd9/.npm/_npx/8873/bin/cgjs
lrwxrwxrwx 1 ewnd9 ewnd9 30 Apr 17 01:08 /home/ewnd9/.npm/_npx/8873/bin/cgjs -> ../lib/node_modules/cgjs/cg.js
```

**Comment by ewnd9** [comment]
Yes, otherwise Node.js module resolution won't be able to resolve node_modules from `bin` directory

**Comment by WebReflection** [comment]
`v0.1.27` with symlinks is out, thanks and sorry for initial misunderstanding.
