### ISSUE TITLE
list of useful npm modules to use with cgjs

### ISSUE THREAD

**Issue by sonnyp** [cgjs/cgjs#17]
I think we should start a list of useful npm modules we use/tested with cgjs. Don't know where to put this so I'm putting this on the wiki for now

https://github.com/cgjs/cgjs/wiki

**Comment by WebReflection** [comment]
wouldn't npm and its list of dependents be enough?

**Comment by WebReflection** [comment]
I had a better look at those two projects: where do you see cgjs in there? both projects seem to have really nothing to do with, what am I missing?

**Comment by sonnyp** [comment]
Never I said these modules used cgjs. I just wanted to list useful modules used/tested with cgjs.

**Comment by WebReflection** [comment]
I see. Is the wiki enough? any action to take?

**Comment by sonnyp** [comment]
I think it would be nice to have them at the end of the README.md with a description, if the list grows too much it can be moved to its own .md or back to the wiki and replaced with a link.

Thought?

**Comment by WebReflection** [comment]
I think having a white list would not give this project any justice. npm has million modules, and of course any module that uses just few parts of the core would work.

Whitelisting few tested modules would give the impression nothing else works. However, CGJS has been created to make GJS software easier through CommonJS and NodeJS core simplified approach, not to be 100% compatible with npm.

That is a non goal of the project so, not sure why we would list those modules.

**Comment by sonnyp** [comment]
Sorry, I didn't explain correctly, I didn't mean just modules that work with cgjs but also are potentially useful with a cgjs project. (Like freedesktop/xdg/... stuff)

I moved it to https://github.com/cgjs/cgjs/wiki/npm-packages, feel free to remove it.

**Comment by ewnd9** [comment]
We need something like [`nodejs/citgm`](https://github.com/nodejs/citgm) to test npm libs continuously.
