### ISSUE TITLE
This application can not open files.

### ISSUE THREAD

**Issue by sonnyp** [cgjs/cgjs#22]
This [gtk-application.js example from gjs](https://github.com/GNOME/gjs/blob/master/examples/gtk-application.js) doesn't run with cgjs and result in

> (gjs:572): GLib-GIO-CRITICAL **: 02:08:41.378: This application can not open files.

It's because with `gjs`, `System.programInvocationName` is `gtk-application.js` and with `cgjs` it is `/home/sonny/.node_modules/bin/cgjs`

**Comment by WebReflection** [comment]
with cgjs is `app.run(process.argv.slice(1))`
