### ISSUE TITLE
Requiring all `GTK_MODULES` instead of only default repository

### ISSUE THREAD

**Issue by ewnd9** [cgjs/cgjs#23]
Right now `require` implementation checks if a module is in `GTK_MODULES` and access it via `imports.gi`:

https://github.com/cgjs/cgjs/blob/a926f7c9476397909624adf89c51db03e894fad5/packages/cgjs/cgjs/require.js#L40-L42

`GTK_MODULES` is defined as:

https://github.com/cgjs/cgjs/blob/a926f7c9476397909624adf89c51db03e894fad5/packages/cgjs/cg.js#L49-L51

On my system I get the following default repository: `GIRepository,GObject,Pango,Gio,xlib,GLib,GModule,GjsPrivate,Gdk,GdkPixbuf,Gtk,cairo,Atk` but this is not a list of all gtk modules, e.g. my favorite `keybinder` module is accessible via `imports.gi.Keybinder` but can't be used in `cgjs` via `require`

---

I propose the following solution: use `Proxy` as I did in my `universal-gtk` experiment:

https://github.com/ewnd9/playground-gtk-javascript/blob/db7b82e4d2961cf51a6ad9c00cd6b81c1bf7f08c/src/universal-gtk/index.js

```js
const gir = new Proxy({}, {
  get(oTarget, name) {
    if (!oTarget[name]) {
      const res = imports.gi[name];

      if (res) {
        oTarget[name] = res; // there should be a camelCase patch
      } else {
        throw new Error(`Can't find ${name}`); // there should be proper cjs error
      }
    }

    return oTarget[name];
  }
});
```

And make it accessible like:

```js
const { Keybinder } = require('cgjs/gi');
```

I understand that this might seem fundamental/controversial issue. There is probably a way to find all gtk modules (instead of just the default repository), but I hope you would agree putting them in a "namespace" is more clean solution instead of the current "global' require.

**Comment by WebReflection** [comment]
the namespace is `gi` already, so that would be the proxy, eventually.

The current solution is based on the assumption that no npm module can ever contain A-Z, which is the case.

I don't find it too difficult to grasp, but a `gi` proxy might also work. too bad there is a `gi` npm module already.

**Comment by ewnd9** [comment]
> The current solution is based on the assumption that no npm module can ever contain A-Z, which is the case.

I initially thought to propose just checking the first character to be upper case instead of a name being in the default repository but then found `xlib` and `cairo` in the list.

**Comment by WebReflection** [comment]
I could use `gir` since it's a known module to basically do the same but in nodejs, hence not suitable ever for gjs at all.

**Comment by ewnd9** [comment]
I still think `cgjs/gi` is better for following Node.js standards, e.g. clicking in editor / [OctoLinker](https://github.com/OctoLinker/OctoLinker) will open the Proxy implementation instead of unrelated module, which might confuse drive-by developers who are considering using `cgjs`

**Comment by ewnd9** [comment]
One more argument: there is a TypeScript typing generator [`sammydre/ts-for-gjs`](https://github.com/sammydre/ts-for-gjs) which is useful even without TypeScript itself (vscode shows autocomplete in JavaScript projects via TypeScript typings). Adopting it to `cgjs` would be confusing with the reusage of existing npm project name.

**Comment by WebReflection** [comment]
if you develop in GJS or CGJS you hopefulyl understand you are not running node. If you don't, and you expect the nodejs module instead, I'm afraid you have bigger issues than a `require('gir')`.

I think `gir` as core module for CGJS makes perfect sense, and I don't have to change any logic to parse slashes for internal modules.

It also landed already via `cgjs 0.1.31` and the previous GTK_MODULES are still there, I might put a warning in the future but actually, at this stage, I don't care much.

**Comment by ewnd9** [comment]
> I think gir as core module for CGJS makes perfect sense, and I don't have to change any logic to parse slashes for internal modules.

If `cgjs` is installed via `node_modules` it shouldn't be an internal module and work without changes. I need to test it though :thinking:

**Comment by WebReflection** [comment]
`gir` is exactly as `fs` and others. It's a core module, it has priority over packages. If you install node-gir it's ok, but you'll never be able to use it via CGJS, which is also OK because it cannot possibly work.

**Comment by WebReflection** [comment]
you can do the same via `const { Gtk } = require('gir');`

**Comment by WebReflection** [comment]
to clarify , cgjs **is** the CommonJS runtime, not something you `require` because `require` wouldn't exist without `cgjs`. It's meant to be used as CLI / executable, like `gjs`, and it would make no sense to `require('gjs')` when you are already running in `gjs`.

Accordingly, having `cgjs` as part of any module name to require looks way more dirty / non-sense than simply having an extra core module for a different env as CGJS is.

It is `gir` and I don't think if you keep proposing `cgjs/anything` I'll change my mind.

**Comment by ewnd9** [comment]
I merely pointed out that you don't have to "change any logic to parse slashes for internal modules." https://github.com/cgjs/cgjs/issues/23#issuecomment-383307593

Apologies if I am too persistent :sweat_smile:
